apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-test9-app279
  namespace: clawtest
  labels:
    app: perf-test9-app279
spec:
  replicas: 1
  selector:
    matchLabels:
      app: perf-test9-app279
  template:
    metadata:
      labels:
        app: perf-test9-app279
    spec:
      containers:
      - name: perf-test9-app279
        image: anolis-registry.cn-zhangjiakou.cr.aliyuncs.com/openanolis/nginx:1.14.1-8.6
        ports:
        - containerPort: 80
        volumeMounts:
        - name: data-vol
          mountPath: /data
      volumes:
      - name: data-vol
        persistentVolumeClaim:
          claimName: perf-test9-app279-pvc
